// Package generator produces static, topic-bound MCP registration code.
package generator

import (
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/dipjyotimetia/kafka-avro-mcp/pkg/jsonschema"
	"github.com/dipjyotimetia/kafka-avro-mcp/pkg/manifest"
)

func Generate(configPath, outDir string) error {
	data, err := os.ReadFile(configPath)
	if err != nil {
		return fmt.Errorf("read manifest: %w", err)
	}
	config, err := manifest.Load(data)
	if err != nil {
		return err
	}
	base := filepath.Dir(configPath)
	type generated struct{ name, tool, schema, input, topic, subject, key, description string }
	events := make([]generated, 0, len(config.Events))
	for _, event := range config.Events {
		schema, err := os.ReadFile(filepath.Join(base, event.Schema))
		if err != nil {
			return fmt.Errorf("read schema for %s: %w", event.Name, err)
		}
		input, err := jsonschema.Convert(schema)
		if err != nil {
			return fmt.Errorf("convert schema for %s: %w", event.Name, err)
		}
		if err := validateKey(event.Kafka.Key.Field, schema); err != nil {
			return fmt.Errorf("validate key for %s: %w", event.Name, err)
		}
		events = append(events, generated{pascal(event.MCP.Tool), event.MCP.Tool, string(schema), string(input), event.Kafka.Topic, event.Kafka.Subject, event.Kafka.Key.Field, event.MCP.Description})
	}
	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by avro-gen-go-mcp; DO NOT EDIT.\npackage %s\n\n", config.Package)
	b.WriteString("import (\n\t\"encoding/json\"\n\n\t\"github.com/dipjyotimetia/kafka-avro-mcp/pkg/runtime\"\n)\n\n")
	for _, event := range events {
		fmt.Fprintf(&b, "var %sTool = runtime.Tool{Name: %s, Topic: %s, Subject: %s, KeyField: %s, Schema: []byte(%s)}\nvar %sInputSchema = json.RawMessage(%s)\n\n", event.name, strconv.Quote(event.tool), strconv.Quote(event.topic), strconv.Quote(event.subject), strconv.Quote(event.key), strconv.Quote(event.schema), event.name, strconv.Quote(event.input))
	}
	b.WriteString("func RegisterTools(server runtime.MCPServer, service *runtime.Service) {\n")
	for _, event := range events {
		fmt.Fprintf(&b, "\truntime.RegisterTool(server, service, %sTool, %sInputSchema, %s)\n", event.name, event.name, strconv.Quote(event.description))
	}
	b.WriteString("}\n")
	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		return fmt.Errorf("format generated source: %w", err)
	}
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return fmt.Errorf("create output directory: %w", err)
	}
	return os.WriteFile(filepath.Join(outDir, "tools.mcp.go"), formatted, 0o644)
}

func validateKey(field string, schema []byte) error {
	if field == "" {
		return nil
	}
	var root struct {
		Fields []struct {
			Name string          `json:"name"`
			Type json.RawMessage `json:"type"`
		} `json:"fields"`
	}
	if err := json.Unmarshal(schema, &root); err != nil {
		return err
	}
	for _, candidate := range root.Fields {
		if candidate.Name != field {
			continue
		}
		var typ string
		if json.Unmarshal(candidate.Type, &typ) != nil || typ != "string" {
			return fmt.Errorf("key field %q must be a non-null Avro string", field)
		}
		return nil
	}
	return fmt.Errorf("key field %q does not exist", field)
}

func pascal(value string) string {
	parts := strings.FieldsFunc(value, func(r rune) bool { return r == '_' || r == '-' || r == '.' })
	for i := range parts {
		parts[i] = strings.ToUpper(parts[i][:1]) + parts[i][1:]
	}
	return strings.Join(parts, "")
}
